### ISSUE TITLE
Training stylegan from scratch: random initialization

### ISSUE THREAD

**Issue by pulkitgo** [matthias-wright/flaxmodels#2]
Hi! I am relatively new to flax, and trying to train the model for stylegan. When I try initializing it using the .init(...) method, I get this error:
 
```bash
flax.errors.SetAttributeFrozenModuleError: Can't set w_avg=[-4.48062038e-03 -2.26424704e-03 -1.13881414e-03  1.17254574e-04
  6.46775961e-03  9.12655238e-03  9.49112512e-03  9.94393881e-03
  4.56054788e-03  4.13127383e-03  8.64951871e-03 -1.31167704e-03
 -1.39767269e-03 -1.31127622e-03  8.68047995e-04 -1.76230317e-03
  ...
 -3.35969799e-03  1.63379814e-02 -3.18925083e-03 -2.73406412e-03] for Module of type MappingNetwork: Module instance is frozen outside of setup method. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.SetAttributeFrozenModuleError)
```

Here is the line which causes the error: 

```python
...
from flaxmodels.stylegan2 import *
from jax import random
...
dummy_z = random.normal(key, (1, 512))
generator = Generator()
params = generator.init(key, dummy_z)['params']    #The problematic line, works the same even without ['params']
...
```

Thanks!

**Comment by matthias-wright** [comment]
Hi @pulkitgo, thanks for pointing this out! 

This was caused by a bug that I just fixed.

Also, keep in mind that in StyleGAN2, the mapping network keeps a running mean of the latent variable W during training.
However, in Flax all variables are immutable while calling `apply`. 

To get around that, you have to declare the collection that contains the running mean as mutable (I asked this [here](https://github.com/google/flax/discussions/1005) a while ago):
```python
images, new_state = generator.apply(params, z, mutable=['moving_stats'])
```
For inference, when you don't want to update the running mean:
```python
images = generator.apply(params, z, train=False)
```
Hope this helps!
