### ISSUE TITLE
Hosting models on a more reliable service

### ISSUE THREAD

**Issue by borisdayma** [matthias-wright/flaxmodels#4]
Hey,

Super cool project!
I discovered it as I plan to try to port [lpips](https://github.com/richzhang/PerceptualSimilarity) to JAX (VGG16 and inference only, no training) and I see that the VGG16 part is already done so only the lpips module needs to be ported.

I noticed that the models were hosted on dropbox. May I suggest to host them on huggingface model hub for more reliability and control (versions, etc)? Also storage is free there so it's probably more interesting!

**Comment by matthias-wright** [comment]
Hi @borisdayma, thanks! Porting LPIPS to Jax sounds great! 
I am definitely open to hosting the pretrained weights somewhere else, if there is a better alternative to dropbox.
I am not very familiar with the model hub from huggingface:
* Is it really free storage or is there a limit on it?
* Is it possible to create a download link, that allows you to download the files via the `requests` package or `wget`?

Thanks for the suggestion!

**Comment by osanseviero** [comment]
Hi @matthias-wright!

> I am not very familiar with the model hub from huggingface:

If you've used git-based workflows, the process to upload pretrained weights should be relatively easy. We wrote a guide for this: https://huggingface.co/docs/hub/adding-a-model

> Is it really free storage or is there a limit on it?

Yes, the storage is free! ✨ 

> Is it possible to create a download link, that allows you to download the files via the requests package or wget?

**Solution 1** Yes, when you upload files, you can download files via usual requests. You can find the download link in the model repo files. [Here](https://huggingface.co/bert-base-uncased/tree/main) is an example. See the download icon for each file.

**Solution 2** A cleaner and nicer solution is using the `huggingface_hub` library. You can read about it [here](https://github.com/huggingface/huggingface_hub/tree/main/src/huggingface_hub), but in short, it allows to programmatically access repositories. It will even handle caching for you so you don't have to re-download the repositories each time. 


This is an example

```python
from huggingface_hub import hf_hub_download
hf_hub_download("flaxmodels/stylegan2_discriminator_afhqcat", filename="weights.h5")
```

cc @LysandreJik @patil-suraj

**Comment by matthias-wright** [comment]
Hi @osanseviero! Thanks for the detailed answer.
Sounds great, I will look into it and report back here.
It is amazing that Huggingface is offering free storage, that is a great service to the research community!

**Comment by matthias-wright** [comment]
I have uploaded the checkpoints for VGG and ResNet to the model hub:
https://huggingface.co/matthias-wright/vgg
https://huggingface.co/matthias-wright/resnet

However, despite of using `git-lfs` I have experienced some issues with uploading larger files.
I have seen error messages such as `error: failed to push some refs to...` as well as `fatal: the remote end hung up unexpectedly`. Sometimes it worked, sometimes it didn't even after several tries.
One issue, which has been explored in [this thread](https://discuss.huggingface.co/t/uploading-files-larger-than-5gb-to-model-hub/4081/8), might be the upload time which exceeds the expiration time in some cases.
This is because the upload rate of my internet connection is mediocre at best.
Since I never experienced any issues with uploading larger files to Dropbox, I will stick to Dropbox for now.
Again, thanks for the suggestion! :+1:

**Comment by elishowk** [comment]
Hello @matthias-wright,

We just deployed a 24h expiration time for uploads.
Even with that in place, one alternative to speed things up is to upload from a server with high-bandwidth instead.

Hope this will improve your experience on the hub.

Regards.
